// InchargeDashboard.jsx

import React, { useState, useEffect, useRef } from 'react';
import {
  FaBell,
  FaHome,
  FaSignOutAlt,
  FaExclamationTriangle,
  FaGavel,
  FaBars,
  FaTimes,
} from 'react-icons/fa';
import { GrAction } from 'react-icons/gr';
import { Link, useNavigate, Routes, Route, useLocation } from 'react-router-dom';
import ProtectedRoute from '../ProtectedRoute';

// Import child pages used by the incharge
import ManageAlerts from '../Admin/ManageAlerts';   // or wherever it actually lives
import DisciplineCases from '../Admin/DisciplineCases';
import Action from '../Admin/Action';

// Tooltip Component
const Tooltip = ({ text }) => (
  <div className="absolute bottom-full mb-2 left-1/3 transform -translate-x-1 px-2 py-1 bg-gray-800 text-white text-sm rounded opacity-0 group-hover:opacity-100 transition-opacity duration-200 pointer-events-none z-10">
    {text}
  </div>
);

// A simple "Home" view for the Incharge
const InchargeHome = () => {
  const [unknownAlerts, setUnknownAlerts] = useState([]);
  const [error, setError] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [selectedAlert, setSelectedAlert] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const itemsPerPage = 3;

  const navigate = useNavigate();

  useEffect(() => {
    fetch('http://13.53.130.198:5000/alerts')
      .then((res) => res.json())
      .then((data) => {
        const unknownOnly = data.filter((alert) => alert.name === 'Unknown');
        setUnknownAlerts(unknownOnly);
      })
      .catch((err) => {
        console.error('Error fetching alerts:', err);
        setError('Error fetching alerts.');
      });
  }, []);

  if (error) {
    return <div>Error: {error}</div>;
  }

  const totalPages = Math.ceil(unknownAlerts.length / itemsPerPage);
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = unknownAlerts.slice(indexOfFirstItem, indexOfLastItem);

  const handlePageChange = (page) => {
    setCurrentPage(page);
  };

  // Basic function to build pagination display
  const generatePageNumbers = () => {
    const pageNumbers = [];
    if (totalPages <= 5) {
      for (let i = 1; i <= totalPages; i++) {
        pageNumbers.push(i);
      }
    } else {
      if (currentPage <= 3) {
        pageNumbers.push(1, 2, 3, 4, '...');
      } else if (currentPage > totalPages - 3) {
        pageNumbers.push('...', totalPages - 3, totalPages - 2, totalPages - 1, totalPages);
      } else {
        pageNumbers.push(
          1,
          '...',
          currentPage - 1,
          currentPage,
          currentPage + 1,
          '...',
          totalPages
        );
      }
    }
    return pageNumbers;
  };

  // Modal-related logic
  const handleTakeAction = (alert) => {
    setSelectedAlert(alert);
    setIsModalOpen(true);
  };

  const handleCancel = () => {
    setIsModalOpen(false);
    setSelectedAlert(null);
  };

  const handleSendOnWhatsApp = () => {
    if (!selectedAlert) return;
    const detectionTime = new Date(selectedAlert.timestamp).toLocaleTimeString();
    const detectionDate = new Date(selectedAlert.timestamp).toLocaleDateString();
    const text = `Detection Alert:\n\nDetection Date: ${detectionDate}\nDetection Time: ${detectionTime}`;
    const imageUrl = `http://13.53.130.198:5000${selectedAlert.additionalInfo.image_path}`;
    const message = `${text}\nImage URL: ${imageUrl}`;
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <>
      <div className="flex lg:flex-row gap-6 w-full flex-col">
        <div className="bg-gradient-to-br from-blue-600/30 to-blue-800/30 p-6 rounded-2xl border border-gray-800/50 shadow-xl flex-1 hover:border-gray-700/50 transition-all duration-300">
          <h2 className="text-xl font-bold mb-3 text-gray-100">Alerts Overview</h2>
          <p className="text-gray-400 mb-5 text-sm leading-relaxed">
            Monitor and manage alerts generated by the system.
          </p>
          <Link
            to="/incharge-dashboard/manage-alerts"
            className="inline-flex items-center px-4 py-2 bg-gray-800/50 border border-gray-700/50 rounded-lg text-gray-300 hover:text-white hover:bg-gray-700/50 hover:border-gray-600/50 transition-all duration-300"
          >
            See All Alerts
            <span className="ml-2 text-blue-400">→</span>
          </Link>
        </div>

        <div className="bg-gradient-to-br from-red-600/30 to-red-800/30 p-6 rounded-2xl border border-gray-800/50 shadow-xl flex-1 hover:border-gray-700/50 transition-all duration-300">
          <h2 className="text-xl font-bold mb-3 text-gray-100">Discipline Cases</h2>
          <p className="text-gray-400 mb-5 text-sm leading-relaxed">
            Review and manage discipline cases and violations.
          </p>
          <Link
            to="/incharge-dashboard/discipline-cases"
            className="inline-flex items-center px-4 py-2 bg-gray-800/50 border border-gray-700/50 rounded-lg text-gray-300 hover:text-white hover:bg-gray-700/50 hover:border-gray-600/50 transition-all duration-300"
          >
            View Violations
            <span className="ml-2 text-red-400">→</span>
          </Link>
        </div>
      </div>

      <div className="mt-8 bg-gray-900/50 p-6 rounded-2xl border border-gray-800/50 shadow-xl">
        <h2 className="text-xl font-bold mb-6 text-gray-200">Most Recent Unknown Person Detected</h2>
        {currentItems.length === 0 ? (
          <p className="text-gray-400">No unknown persons detected.</p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {currentItems.map((alert, index) => (
              <div
                key={index}
                className="p-6 bg-gradient-to-br from-red-700/50 to-red-800/50 rounded-2xl border border-red-800/50 shadow-lg hover:border-red-700/50 transition-all duration-300"
              >
                <p className="text-gray-300 mb-3">
                  {new Date(alert.timestamp).toLocaleString()}
                </p>
                {alert.additionalInfo?.image_path && (
                  <img
                    src={`http://13.53.130.198:5000${alert.additionalInfo.image_path}`}
                    alt="Unknown Person"
                    className="rounded-xl shadow-md w-full mb-4"
                  />
                )}
                <button
                  onClick={() => handleTakeAction(alert)}
                  className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-6 rounded-lg transition-all duration-300 shadow-lg hover:shadow-blue-500/20 hover:scale-[1.02]"
                >
                  Take Action
                </button>
              </div>
            ))}
          </div>
        )}

        <div className="flex justify-center mt-8">
          <button
            onClick={() => navigate('/incharge-dashboard/action')}
            className="px-6 py-2 border border-gray-700/50 text-blue-400 rounded-lg hover:bg-gray-800/50 hover:border-gray-600/50 transition-all duration-300"
          >
            View All
          </button>
        </div>
      </div>

      {isModalOpen && selectedAlert && (
        <div className="fixed inset-0 flex items-center justify-center z-50 bg-black/50 backdrop-blur-sm">
          <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-8 rounded-2xl border border-gray-700/50 shadow-2xl max-w-lg w-full">
            <h2 className="text-2xl font-bold mb-6 text-gray-100">Take Action</h2>
            <div className="mb-6">
              <img
                src={`http://13.53.130.198:5000${selectedAlert.additionalInfo.image_path}`}
                alt="Unknown Person"
                className="w-full rounded-xl shadow-md mb-4"
              />
              <div className="space-y-2 text-gray-300">
                <p>
                  <span className="font-semibold">Detection Date:</span>{' '}
                  {new Date(selectedAlert.timestamp).toLocaleDateString()}
                </p>
                <p>
                  <span className="font-semibold">Detection Time:</span>{' '}
                  {new Date(selectedAlert.timestamp).toLocaleTimeString()}
                </p>
              </div>
            </div>
            <div className="flex justify-between space-x-4">
              <button
                onClick={handleCancel}
                className="flex-1 bg-gray-700/50 hover:bg-gray-600/50 text-white font-semibold py-3 rounded-lg transition-all duration-300 border border-gray-600/50"
              >
                Cancel
              </button>
              <button
                onClick={handleSendOnWhatsApp}
                className="flex-1 bg-gradient-to-r from-green-600 to-green-700 hover:from-green-500 hover:to-green-600 text-white font-semibold py-3 rounded-lg transition-all duration-300 shadow-lg hover:shadow-green-500/20"
              >
                WhatsApp Alert
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};


const InchargeDashboard = () => {
  const [showNotifications, setShowNotifications] = useState(false);
  const [realTimeNotification, setRealTimeNotification] = useState([]);
  const notificationsRef = useRef(null);
  const navigate = useNavigate();
  const location = useLocation();

  // State for Sidebar
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen);

  // ------------------ WEBSOCKET for Real-Time Alerts ------------------
  useEffect(() => {
    const ws = new WebSocket('ws://localhost:8080');

    ws.onmessage = (event) => {
      const newAlert = JSON.parse(event.data);
      console.log('New alert received:', newAlert);

      // Keep only the last 5 notifications
      setRealTimeNotification((prev) => {
        const updated = [...prev, newAlert];
        if (updated.length > 5) updated.shift();
        return updated;
      });
    };

    ws.onclose = () => {
      console.log('WebSocket closed');
    };

    return () => ws.close();
  }, []);

  // ------------------ NOTIFICATION DROPDOWN BEHAVIOR ------------------
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (
        notificationsRef.current &&
        !notificationsRef.current.contains(event.target)
      ) {
        setShowNotifications(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleBellClick = () => {
    setShowNotifications(!showNotifications);
    if (showNotifications) {
      setRealTimeNotification([]);
    }
  };

  const handleNotificationClick = () => {
    setShowNotifications(false);
    navigate('/incharge-dashboard/manage-alerts');
  };

  const handleSignOut = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('userType');
    navigate('/login');
  };

  // --------------- SIDEBAR MENU ITEMS ---------------
  const menuItems = [
    {
      name: 'Home',
      icon: <FaHome className="mr-3" />,
      link: '/incharge-dashboard',
      tooltip: 'Dashboard Home',
    },
    {
      name: 'View Alerts',
      icon: <FaExclamationTriangle className="mr-3" />,
      link: '/incharge-dashboard/manage-alerts',
      tooltip: 'Review alerts sent by model',
    },
    {
      name: 'Violations',
      icon: <FaGavel className="mr-3" />,
      link: '/incharge-dashboard/discipline-cases',
      tooltip: 'See discipline cases and violations',
    },
    {
      name: 'Action',
      icon: <GrAction className="mr-3" />,
      link: '/incharge-dashboard/action',
      tooltip: 'Go for detailed actions',
    },
  ];

  // Determine if a link is currently active
  const isActive = (path) => location.pathname === path;

  return (
    <ProtectedRoute>
      <div className="flex flex-col min-h-screen bg-gradient-to-br from-gray-900 to-gray-800">
        <header className="bg-gradient-to-r from-gray-800 to-gray-900 p-4 md:p-6 shadow-xl flex flex-col md:flex-row justify-between items-center sticky top-0 z-50">
          <div className="flex items-center w-full justify-between">
            <div className="flex items-center space-x-4">
              <div className="h-12 w-12 md:h-16 md:w-16 transition-transform duration-300 hover:scale-105">
                <img
                  src="/face-trace-logo.png"
                  alt="Logo"
                  className="object-contain h-full w-full drop-shadow-lg"
                />
              </div>
              <h1 className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
                Security In-Charge Dashboard
              </h1>
            </div>

            <div className="md:hidden relative group">
              <button
                onClick={toggleSidebar}
                className="p-2 rounded-lg bg-gray-700 hover:bg-gray-600 transition-all duration-300"
              >
                {isSidebarOpen ? (
                  <FaTimes className="text-white text-xl" />
                ) : (
                  <FaBars className="text-white text-xl" />
                )}
              </button>
              <Tooltip text={isSidebarOpen ? 'Close Sidebar' : 'Open Sidebar'} />
            </div>
          </div>

          <div className="flex items-center space-x-4 mt-4 md:mt-0 w-full justify-end">
            <div className="relative group" ref={notificationsRef}>
              <div className="relative">
                <FaBell
                  className="text-white text-2xl cursor-pointer hover:text-blue-400 transition-colors duration-200"
                  onClick={handleBellClick}
                />
                {realTimeNotification.length > 0 && !showNotifications && (
                  <span className="absolute -top-1 -right-2 bg-red-500 rounded-full w-5 h-5 text-xs flex items-center justify-center font-bold text-white animate-pulse">
                    {realTimeNotification.length}
                  </span>
                )}
              </div>
              <Tooltip text="Notifications" />

              {showNotifications && (
                <div className="absolute right-0 mt-2 w-72 md:w-80 bg-gray-800 backdrop-blur-lg border border-gray-700 text-white shadow-2xl rounded-xl overflow-hidden z-50 transform transition-all duration-300 origin-top">
                  <div className="p-2 bg-gray-900 border-b border-gray-700">
                    <h3 className="text-sm font-semibold text-blue-400">Recent Alerts</h3>
                  </div>
                  {realTimeNotification.map((alert, idx) => (
                    <div
                      key={idx}
                      className="p-4 hover:bg-gray-700/50 cursor-pointer border-b border-gray-700/30 last:border-b-0 transition-colors duration-200"
                      onClick={handleNotificationClick}
                    >
                      <div className="flex items-center space-x-3">
                        <div className="h-2 w-2 bg-red-500 rounded-full animate-pulse" />
                        <div>
                          <p className="text-sm font-medium">Unknown Person Detected</p>
                          <p className="text-xs text-gray-400 mt-1">
                            {new Date(alert.timestamp).toLocaleString()}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                  {realTimeNotification.length === 0 && (
                    <div className="p-4 text-sm text-gray-400">No new notifications</div>
                  )}
                </div>
              )}
            </div>

            <button
              className="group bg-gradient-to-r from-red-600 to-red-700 hover:from-red-500 hover:to-red-600 text-white px-4 py-2 rounded-lg flex items-center space-x-2 transition-all duration-300 shadow-lg hover:shadow-red-500/20"
              onClick={handleSignOut}
            >
              <FaSignOutAlt className="text-lg" />
              <span className="hidden md:inline">Sign Out</span>
            </button>
          </div>
        </header>

        <div className="flex flex-1">
          <aside
            className={`fixed inset-y-0 left-0 transform ${
              isSidebarOpen ? 'translate-x-0' : '-translate-x-full'
            } md:translate-x-0 md:static w-64 text-white p-6 space-y-6 transition-all duration-300 z-50 bg-gray-900 shadow-2xl border-r border-gray-800`}
          >
            <nav>
              <ul className="space-y-3">
                {menuItems.map((item) => (
                  <li key={item.link} className="relative group">
                    <Link
                      to={item.link}
                      className={`flex items-center space-x-3 p-3 rounded-xl transition-all duration-200 ${
                        isActive(item.link)
                          ? 'bg-blue-600/30 border border-blue-500/50 text-blue-400'
                          : 'hover:bg-gray-800/50 hover:border-gray-700/50 border border-transparent'
                      }`}
                      onClick={() => setIsSidebarOpen(false)}
                    >
                      <span className="text-lg">{item.icon}</span>
                      <span className="text-sm font-medium">{item.name}</span>
                    </Link>
                    <Tooltip text={item.tooltip} />
                  </li>
                ))}
              </ul>
            </nav>
          </aside>

          {isSidebarOpen && (
            <div
              className="fixed inset-0 bg-black/50 backdrop-blur-sm z-40 md:hidden"
              onClick={toggleSidebar}
            />
          )}

          <main className="flex-1 p-4 md:p-8 overflow-auto">
            <Routes>
              <Route path="/manage-alerts" element={<ManageAlerts />} />
              <Route path="/discipline-cases" element={<DisciplineCases />} />
              <Route path="/action" element={<Action />} />
              <Route path="/" element={<InchargeHome />} />
            </Routes>
          </main>
        </div>
      </div>
    </ProtectedRoute>
  );
};

export default InchargeDashboard;
